Repository Hu-Fi/Mr.Market, pull requests merged in 2024-11, with the labels that each got.

#259 fix: add migration
  server/src/database/migrations/1730464574077-strategyEntity.ts
  server/yarn.lock
Labels: Review effort [1-5]: 2

#263 Add web3 address field when create a grow order
  interface/package.json
  interface/src/assets/news/news-EN.json
  interface/src/assets/news/news-ZH.json
  interface/src/i18n/en.json
  interface/src/lib/components/common/web3Address.svelte
  interface/src/lib/components/dialogs/grow/growAddMore.svelte
  interface/src/lib/components/grow/arbitrage/new/confirm.svelte
  interface/src/lib/components/grow/arbitrage/new/pair.svelte
  interface/src/lib/components/grow/justGrow/new/amount.svelte
  interface/src/lib/components/grow/justGrow/new/time.svelte
  interface/src/lib/components/spot/spot.svelte
  interface/src/lib/components/wallet/wallet.svelte
  interface/src/lib/helpers/constants.ts
  interface/src/lib/helpers/validateAddress.ts
  interface/src/lib/stores/grow.ts
  interface/src/routes/(secondary)/(grow)/grow/just_grow/new/two/+page.svelte
  interface/src/routes/(secondary)/(grow)/grow/market_making/new/two/+page.svelte
  interface/tests/grow/just-grow.spec.ts
  interface/yarn.lock
  server/src/common/constants/pairs.ts
  server/src/modules/marketdata/marketdata.gateway.ts
Labels: Review effort [1-5]: 3

#265 Add currency rate
  interface/package.json
  interface/src/lib/components/home/walletBalance/balance.svelte
  interface/src/lib/helpers/constants.ts
  interface/src/lib/helpers/currency/currency.test.ts
  interface/src/lib/helpers/currency/currency.ts
  interface/src/lib/helpers/sortTable.ts
  interface/src/lib/helpers/utils.test.ts
  interface/src/lib/stores/wallet.ts
  interface/src/lib/types/hufi/wallet.ts
  server/src/app.module.ts
  server/yarn.lock
Labels: Review effort [1-5]: 3

#266 multiple fixes to strategy service
  server/src/modules/strategy/strategy.service.ts
Labels: Review effort [1-5]: 4

#267 Join Strategy and verify transaction
  server/src/app.module.ts
  server/src/common/entities/contribution.entity.ts
  server/src/common/entities/mixin-user.entity.ts
  server/src/common/entities/strategy-instances.entity.ts
  server/src/modules/admin/admin.controller.ts
  server/src/modules/admin/admin.module.ts
  server/src/modules/admin/admin.service.spec.ts
  server/src/modules/admin/admin.service.ts
  server/src/modules/strategy/strategy.controller.spec.ts
  server/src/modules/strategy/strategy.controller.ts
  server/src/modules/strategy/strategy.dto.ts
  server/src/modules/strategy/strategy.module.ts
  server/src/modules/strategy/strategy.service.spec.ts
  server/src/modules/strategy/strategy.service.ts
  server/src/modules/web3/web3.service.ts
Labels: Review effort [1-5]: 4

#268 feat: add migration
  server/src/database/migrations/1731671515679-updateContribution.ts
Labels: Review effort [1-5]: 3

#275 Keep Probit Connected
  server/src/modules/exchangeInit/exchangeInit.service.ts
Labels: Review effort [1-5]: 3

#278 feat: add discord log webhook
  server/.env.example
  server/src/app.controller.ts
  server/src/common/helpers/utils.spec.ts
  server/src/modules/admin/admin.service.spec.ts
  server/src/modules/auth/auth.controller.ts
  server/src/modules/auth/auth.service.spec.ts
  server/src/modules/campaign/campaign.service.ts
  server/src/modules/exchangeInit/exchangeInit.service.ts
  server/src/modules/logger/logger.service.ts
  server/src/modules/marketdata/marketdata.gateway.ts
  server/src/modules/marketdata/marketdata.service.ts
  server/src/modules/mixin/listeners/spot.listener.ts
  server/src/modules/mixin/message/message.service.ts
  server/src/modules/mixin/rebalance/rebalance.repository.ts
  server/src/modules/mixin/rebalance/rebalance.service.spec.ts
  server/src/modules/mixin/rebalance/rebalance.service.ts
  server/src/modules/strategy/strategy.controller.spec.ts
  server/src/modules/strategy/strategy.service.spec.ts
  server/src/modules/strategy/strategy.service.ts
Labels: Review effort [1-5]: 4

#281 feat: add mixin webook to logger
  server/.env.example
  server/src/modules/logger/logger.service.ts
  server/src/modules/mixin/exchange/exchange.service.ts
  server/src/modules/mixin/message/message.service.ts
  server/src/modules/mixin/rebalance/rebalance.service.ts
  server/src/modules/mixin/snapshots/snapshots.service.ts
  server/src/modules/strategy/strategy-user.service.ts
  server/src/modules/strategy/strategy.service.ts
Labels: Review effort [1-5]: 3

#282 feat: send warn/error to discord
  server/src/modules/logger/logger.service.ts
Labels: Review effort [1-5]: 2
