Repository Hu-Fi/Mr.Market, pull requests merged in 2024-12, with the labels that each got.

#283 Improve log & Fix entity import
  server/src/app.controller.spec.ts
  server/src/app.controller.ts
  server/src/app.module.ts
  server/src/app.service.ts
  server/src/common/helpers/blockchain-utils.ts
  server/src/common/helpers/mixin/user.ts
  server/src/main.ts
  server/src/modules/auth/auth.controller.ts
  server/src/modules/campaign/campaign.service.ts
  server/src/modules/exchangeInit/exchangeInit.service.ts
  server/src/modules/logger/logger.service.ts
  server/src/modules/marketdata/marketdata.gateway.ts
  server/src/modules/marketdata/marketdata.service.ts
  server/src/modules/mixin/exchange/exchange.service.ts
  server/src/modules/mixin/listeners/arbitrage.listener.ts
  server/src/modules/mixin/listeners/market_making.listener.ts
  server/src/modules/mixin/listeners/spot.listener.ts
  server/src/modules/mixin/message/message.service.ts
  server/src/modules/mixin/rebalance/rebalance.repository.ts
  server/src/modules/mixin/rebalance/rebalance.service.ts
  server/src/modules/mixin/snapshots/snapshots.service.ts
  server/src/modules/mixin/user/user.service.ts
  server/src/modules/strategy/alpacastrat.service.ts
  server/src/modules/strategy/strategy-user.service.ts
  server/src/modules/strategy/strategy.service.ts
Labels: Review effort [1-5]: 4

#286 fix: mm order tracking
  server/package.json
  server/src/modules/strategy/strategy.service.ts
Labels: Review effort [1-5]: 3

#291 fix: migration scripts
  server/src/database/migrations/1730464574077-strategyEntity.ts
  server/src/database/migrations/1731671515679-updateContribution.ts
  server/src/database/migrations/1732716866030-initialSetup.ts
  server/src/database/migrations/1733923487142-updateGrowOrders.ts
  server/typeorm.config.ts
Labels: Review effort [1-5]: 4

#292 fix: ssl error when seed
  server/src/database/seeder/seed.ts
Labels: Review effort [1-5]: 2

#294 feat: save start price of the symbol for stategy
  server/src/common/entities/strategy-instances.entity.ts
  server/src/database/migrations/1734370164914-addStartPriceToStrategyInstance.ts
  server/src/modules/strategy/strategy.service.ts
Labels: Review effort [1-5]: 3

#295 feat: basic metrics of strategy
  server/src/app.module.ts
  server/src/modules/metrics/metrics/metrics.controller.spec.ts
  server/src/modules/metrics/metrics/metrics.controller.ts
  server/src/modules/metrics/metrics/metrics.module.ts
  server/src/modules/metrics/metrics/metrics.service.spec.ts
  server/src/modules/metrics/metrics/metrics.service.ts
Labels: Review effort [1-5]: 4

#296 Update probit initialization and descriptions
  server/src/modules/admin/strategy/adminStrategy.service.spec.ts
  server/src/modules/admin/strategy/adminStrategy.service.ts
  server/src/modules/exchangeInit/exchangeInit.service.ts
  server/src/modules/strategy/strategy.controller.ts
  server/src/modules/strategy/strategy.dto.ts
  server/src/modules/strategy/strategy.service.ts
Labels: Review effort [1-5]: 4
