Repository Hu-Fi/Mr.Market, pull requests merged in 2024-03, with the labels that each got.

#32 add pr-review
  .github/workflows/ai-review.yml
  .github/workflows/lint.yml
  .github/workflows/playwright.yml
  .github/workflows/vitest.yml
Labels: enhancement, Review effort [1-5]: 2, Possible security concern

#34 test server tests
  .github/workflows/servertests.yml
Labels: Review effort [1-5]: 1, Tests

#47 Add load constants from .env for frontend
  interface/.env.example
  interface/src/lib/helpers/constants.ts
  interface/tsconfig.json
Labels: enhancement, Review effort [1-5]: 2

#55 move to local backend for tests
  .github/workflows/playwright.yml
  interface/.env.example
  interface/playwright.config.ts
  interface/src/lib/components/topBar/homeBar.svelte
  interface/src/lib/helpers/constants.ts
  interface/src/lib/helpers/hufi/coin.test.ts
  interface/tests/grow/grow.spec.ts
  interface/tests/home/home.spec.ts
  interface/tests/swap/swap.spec.ts
  interface/tests/trade/order.spec.ts
  interface/tests/trade/trade.spec.ts
  interface/tsconfig.json
  server/src/modules/trade/trade.service.ts
Labels: documentation, enhancement, Tests, Review effort [1-5]: 3

#58 Try to fix railway
  server/package.json
  server/yarn.lock
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#59 Add a railway badge
  README.md
Labels: documentation, Review effort [1-5]: 1

#56 Add campaign launching scripts
  scripts/campaign_launcher.ts
  scripts/campaign_launcher_tests.ts
  scripts/fetch_campaigns.ts
Labels: enhancement, Tests, Review effort [1-5]: 4

#57 Strategy modifcations
  README.md
  package.json
  server/.gitignore
  server/src/app.module.ts
  server/src/modules/logger/logger.service.ts
  server/src/modules/marketdata/marketdata.gateway.ts
  server/src/modules/strategy/strategy.dto.ts
  server/src/modules/strategy/strategy.service.ts
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#61 Update README.md
  README.md
Labels: documentation, Review effort [1-5]: 1

#63 Update README.md
  README.md
Labels: documentation, enhancement, Review effort [1-5]: 1

#99 add user controller
  server/src/common/helpers/checks/spotChecks.ts
  server/src/modules/mixin/user/user.controller.ts
  server/src/modules/mixin/user/user.module.ts
Labels: enhancement, Review effort [1-5]: 2

#101 Add getting all sport orders to exchange module + controller
  server/src/modules/mixin/exchange/exchange.controller.spec.ts
  server/src/modules/mixin/exchange/exchange.controller.ts
  server/src/modules/mixin/exchange/exchange.module.ts
  server/src/modules/mixin/exchange/exchange.repository.ts
  server/src/modules/mixin/exchange/exchange.service.ts
Labels: enhancement, Review effort [1-5]: 2, Tests
