Repository Hu-Fi/Mr.Market, pull requests merged in 2024-05, with the labels that each got.

#166 Configure render
  README.md
  render.yaml
Labels: enhancement, Review effort [1-5]: 2, Configuration changes

#174 update README and create makefile for easier dev environment setup
  .github/workflows/lint.yml
  .github/workflows/playwright.yml
  .github/workflows/vitest.yml
  Makefile
  README.md
  interface/.eslintignore
  interface/package-lock.json
  interface/package.json
  interface/playwright.config.ts
  interface/src/lib/helpers/hufi/coin.ts
  interface/vite.config.ts
  interface/yarn.lock
  package.json
  server/.gitignore
  server/docker-compose-dev.yaml
  server/package.json
  server/yarn.lock
Labels: documentation, enhancement, bug_fix, Review effort [1-5]: 3

#175 Add manual strategy execution.
  server/src/modules/health/health.service.spec.ts
  server/src/modules/health/health.service.ts
  server/src/modules/strategy/strategy.controller.ts
Labels: enhancement, Review effort [1-5]: 3

#182 update deployment link
  README.md
Labels: documentation, enhancement, Review effort [1-5]: 1

#181 remove scripts
  scripts/campaign_launcher.ts
  scripts/campaign_launcher_tests.ts
  scripts/fetch_campaigns.ts
Labels: Review effort [1-5]: 1, other
