Repository Hu-Fi/Mr.Market, pull requests merged in 2024-07, with the labels that each got.

#205 Add more exchanges
  server/.env.example
  server/src/app.module.ts
  server/src/modules/exchangeInit/exchangeInit.service.ts
  server/src/modules/marketdata/marketdata.module.ts
  server/src/modules/marketdata/marketdata.service.spec.ts
  server/src/modules/marketdata/marketdata.service.ts
Labels: enhancement, Tests, Review effort [1-5]: 3, Configuration changes

#206 Fix stop issues
  server/.env.example
  server/src/modules/exchangeInit/exchangeInit.service.ts
  server/src/modules/strategy/strategy-user.service.spec.ts
  server/src/modules/strategy/strategy.controller.spec.ts
  server/src/modules/strategy/strategy.controller.ts
  server/src/modules/strategy/strategy.module.ts
  server/src/modules/strategy/strategy.service.ts
Labels: documentation, enhancement, Tests, Review effort [1-5]: 4

#207 Revert "Fix stop issues"
  server/.env.example
  server/src/modules/exchangeInit/exchangeInit.service.ts
  server/src/modules/strategy/strategy-user.service.spec.ts
  server/src/modules/strategy/strategy.controller.spec.ts
  server/src/modules/strategy/strategy.controller.ts
  server/src/modules/strategy/strategy.module.ts
  server/src/modules/strategy/strategy.service.ts
Labels: enhancement, Tests, Review effort [1-5]: 4, Bug fix

#209 fix stop strategy problem
  server/src/modules/strategy/strategy.controller.ts
Labels: Review effort [1-5]: 2, Bug fix

#212 Fix trade not executing issues
  server/src/modules/trade/trade.module.ts
  server/src/modules/trade/trade.service.spec.ts
  server/src/modules/trade/trade.service.ts
Labels: Tests, Review effort [1-5]: 3, Bug fix
