Repository Hu-Fi/Mr.Market, pull requests merged in 2024-06, with the labels that each got.

#157 Add deployment guide
  README.md
Labels: documentation, enhancement, Review effort [1-5]: 2

#197 add comment for all service files
  server/src/modules/auth/auth.service.ts
  server/src/modules/coingecko/coingecko.service.ts
  server/src/modules/customConfig/customConfig.service.ts
  server/src/modules/health/health.service.ts
  server/src/modules/logger/logger.service.ts
  server/src/modules/marketdata/marketdata.service.ts
  server/src/modules/mixin/exchange/exchange.service.ts
  server/src/modules/mixin/listeners/arbitrage.listener.ts
  server/src/modules/mixin/listeners/exchange.listener.ts
  server/src/modules/mixin/listeners/market_making.listener.ts
  server/src/modules/mixin/listeners/mixin.listener.ts
  server/src/modules/mixin/listeners/spot.listener.ts
  server/src/modules/mixin/message/message.service.ts
  server/src/modules/mixin/rebalance/bigone/bigone.service.ts
  server/src/modules/mixin/rebalance/rebalance.service.ts
  server/src/modules/mixin/snapshots/snapshots.service.ts
  server/src/modules/mixin/user/user.service.ts
  server/src/modules/performance/performance.service.ts
  server/src/modules/strategy/strategy.service.ts
  server/src/modules/trade/trade.service.ts
Labels: documentation, Review effort [1-5]: 2

#196 Auth flow
  README.md
  interface/src/lib/components/admin/login.svelte
  interface/src/lib/components/common/connectWalletBtn.svelte
  interface/src/lib/components/home/user/username.svelte
  interface/src/lib/components/spot/bids/inputs.svelte
  interface/src/lib/helpers/hufi/auth.ts
  interface/src/lib/helpers/mixin-oauth.ts
  interface/src/lib/helpers/mixin.ts
  server/.env.example
  server/src/common/constants/constants.ts
  server/src/common/entities/mixin-user.entity.ts
  server/src/common/helpers/mixin/user.ts
  server/src/config/configuration.ts
  server/src/modules/auth/auth.controller.ts
  server/src/modules/auth/auth.module.ts
  server/src/modules/auth/auth.service.spec.ts
  server/src/modules/auth/auth.service.ts
  server/src/modules/health/health.service.spec.ts
  server/src/modules/mixin/message/message.module.ts
  server/src/modules/mixin/rebalance/rebalance.module.ts
  server/src/modules/mixin/rebalance/rebalance.repository.ts
  server/src/modules/mixin/rebalance/rebalance.service.spec.ts
  server/src/modules/mixin/rebalance/rebalance.service.ts
  server/src/modules/mixin/user/user.repository.ts
  server/src/modules/mixin/user/user.service.ts
Labels: enhancement, Tests, Review effort [1-5]: 4, Bug fix

#204 Add more exchange support
  server/.env.example
  server/src/app.module.ts
  server/src/modules/exchangeInit/exchangeInit.module.ts
  server/src/modules/exchangeInit/exchangeInit.service.spec.ts
  server/src/modules/exchangeInit/exchangeInit.service.ts
  server/src/modules/strategy/strategy.module.ts
  server/src/modules/strategy/strategy.service.spec.ts
  server/src/modules/strategy/strategy.service.ts
Labels: enhancement, Tests, Review effort [1-5]: 3
