Repository Hu-Fi/Mr.Market, pull requests merged in 2024-04, with the labels that each got.

#110 Add order details and history page
  interface/package-lock.json
  interface/package.json
  interface/src/i18n/en.json
  interface/src/lib/components/common/connectWalletBtn.svelte
  interface/src/lib/components/dialogs/candle/candlePairSelector.svelte
  interface/src/lib/components/dialogs/manageOrder/cancelOrder.svelte
  interface/src/lib/components/dialogs/orderConfirm.svelte
  interface/src/lib/components/home/markets/coins.svelte
  interface/src/lib/components/home/oauth/connectMixin.svelte
  interface/src/lib/components/spot/bids/inputs.svelte
  interface/src/lib/components/spot/history/historys.svelte
  interface/src/lib/components/spot/history/orderDetail.svelte
  interface/src/lib/components/spot/history/singleSpotHistory.svelte
  interface/src/lib/components/spot/manage/openOrders.svelte
  interface/src/lib/components/spot/manage/singleOrder.svelte
  interface/src/lib/components/spot/manage/tabs.svelte
  interface/src/lib/components/topBar/spotHistoryBar.svelte
  interface/src/lib/components/topBar/spotHistoryDetailBar.svelte
  interface/src/lib/components/wallet/connect/connectWallet.svelte
  interface/src/lib/helpers/hufi/coin.ts
  interface/src/lib/helpers/hufi/spot.ts
  interface/src/lib/helpers/mixin.ts
  interface/src/lib/helpers/utils.ts
  interface/src/lib/stores/spot.ts
  interface/src/lib/stores/wallet.ts
  interface/src/lib/types/hufi/spot.ts
  interface/src/routes/(secondary)/(spot)/spot/history/+page.svelte
  interface/src/routes/(secondary)/(spot)/spot/history/[id]/+page.ts
  server/src/common/entities/spot-order.entity.ts
  server/src/common/helpers/checks/spotChecks.ts
  server/src/common/helpers/mixin/memo.spec.ts
  server/src/common/helpers/mixin/memo.ts
  server/src/common/helpers/utils.ts
  server/src/common/types/memo/memo.ts
  server/src/common/types/orders/states.ts
  server/src/modules/mixin/events/spot.event.ts
  server/src/modules/mixin/exchange/exchange-client.controller.ts
  server/src/modules/mixin/exchange/exchange.module.ts
  server/src/modules/mixin/exchange/exchange.repository.ts
  server/src/modules/mixin/exchange/exchange.service.ts
  server/src/modules/mixin/listeners/exchange.listener.spec.ts
  server/src/modules/mixin/listeners/exchange.listener.ts
  server/src/modules/mixin/listeners/spot.listener.spec.ts
  server/src/modules/mixin/listeners/spot.listener.ts
  server/src/modules/mixin/snapshots/snapshots.service.ts
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#117 Revert "73 - implementing coin gecko category filter"
  interface/src/lib/components/home/markets/coins.svelte
  interface/src/lib/components/home/markets/tabs.svelte
  interface/src/lib/components/search/search.svelte
  interface/src/lib/helpers/constants.ts
  interface/src/lib/helpers/hufi/coin.ts
  interface/src/lib/stores/market.ts
  interface/src/routes/(bottomNav)/(market)/market/token/+page.svelte
  interface/src/routes/+layout.ts
  server/src/modules/coingecko/coingecko.controller.ts
  server/src/modules/coingecko/coingecko.service.spec.ts
  server/src/modules/coingecko/coingecko.service.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#109 Create arbitrage and market making UI
  interface/src/i18n/en.json
  interface/src/lib/components/bottomNav/growNewArbNav.svelte
  interface/src/lib/components/bottomNav/growNewAutoInvestNav.svelte
  interface/src/lib/components/bottomNav/growNewMMNav.svelte
  interface/src/lib/components/dialogs/bottomTrade.svelte
  interface/src/lib/components/dialogs/grow/arbitrage/confirmPayment.svelte
  interface/src/lib/components/dialogs/grow/arbitrage/selectExchange.svelte
  interface/src/lib/components/dialogs/grow/arbitrage/selectPair.svelte
  interface/src/lib/components/dialogs/grow/market_making/confirmPayment.svelte
  interface/src/lib/components/grow/arbitrage/new/easy/exchanges.svelte
  interface/src/lib/components/grow/elements/entrance.svelte
  interface/src/lib/components/grow/marketMaking/new/easy/amount.svelte
  interface/src/lib/components/grow/marketMaking/new/easy/exchange.svelte
  interface/src/lib/components/grow/marketMaking/new/easy/pair.svelte
  interface/src/lib/helpers/constants.ts
  interface/src/lib/helpers/memo.ts
  interface/src/lib/helpers/mixin.ts
  interface/src/lib/stores/grow.ts
  interface/src/lib/stores/spot.ts
  interface/src/routes/(secondary)/(grow)/grow/arbitrage/new/+layout@.svelte
  interface/src/routes/(secondary)/(grow)/grow/arbitrage/new/easy/+page.svelte
  interface/src/routes/(secondary)/(grow)/grow/market_making/new/+layout@.svelte
  interface/src/routes/(secondary)/(grow)/grow/market_making/new/easy/two/+page.svelte
  server/src/common/constants/memo.ts
  server/src/common/helpers/mixin/memo.ts
  server/src/common/types/memo/memo.ts
  server/src/modules/mixin/snapshots/snapshots.service.ts
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#130 Fix #119 filter in market page
  interface/src/i18n/en.json
  interface/src/i18n/zh.json
  interface/src/lib/components/home/markets/tabs.svelte
  interface/src/lib/components/market/elements/secondTabs.svelte
  interface/src/lib/components/market/token/singlePair.svelte
  interface/src/lib/components/skeleton/market/tokenFilterLoader.svelte
  interface/src/lib/components/spot/history/orderDetail.svelte
  interface/src/lib/helpers/constants.ts
  interface/src/lib/helpers/utils.ts
  interface/src/lib/stores/home.ts
  interface/src/lib/stores/market.ts
  interface/src/routes/(bottomNav)/(market)/market/spot/+page.svelte
  interface/src/routes/(bottomNav)/(market)/market/token/+page.svelte
  server/src/modules/coingecko/coingecko.controller.ts
  server/src/modules/coingecko/coingecko.service.spec.ts
  server/src/modules/coingecko/coingecko.service.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#133 disable dark mode
  interface/src/lib/components/home/user/settings.svelte
  interface/src/routes/+layout.svelte
Labels: enhancement, Review effort [1-5]: 2

#142 fix bot id constant
  interface/src/lib/helpers/constants.ts
Labels: enhancement, Review effort [1-5]: 1

#143 Fix snapshot handler bugs
  interface/src/lib/components/dialogs/grow/arbitrage/confirmPayment.svelte
  interface/src/lib/components/dialogs/grow/market_making/confirmPayment.svelte
  interface/src/lib/helpers/memo.test.ts
  interface/src/lib/helpers/memo.ts
  server/.env.example
  server/src/common/entities/snapshots.entity.ts
  server/src/config/configuration.ts
  server/src/modules/auth/auth.service.spec.ts
  server/src/modules/mixin/listeners/arbitrage.listener.ts
  server/src/modules/mixin/listeners/market_making.listener.ts
  server/src/modules/mixin/snapshots/snapshots.repository.ts
  server/src/modules/mixin/snapshots/snapshots.service.spec.ts
  server/src/modules/mixin/snapshots/snapshots.service.ts
  server/src/modules/strategy/strategy-user.service.spec.ts
  server/src/modules/strategy/strategy-user.service.ts
  server/src/modules/strategy/strategy.module.ts
  server/src/modules/strategy/strategy.service.ts
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#144 Add strategy orders and fetching for Order History Page
  server/src/app.module.ts
  server/src/common/entities/arbitrage-order.entity.ts
  server/src/common/entities/order.entity.ts
  server/src/modules/strategy/orders.controller.ts
  server/src/modules/strategy/strategy.module.ts
  server/src/modules/strategy/strategy.service.spec.ts
  server/src/modules/strategy/strategy.service.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#145 Fix issue with arbitrage order
  server/src/app.module.ts
  server/src/common/entities/arbitrage-order.entity.ts
  server/src/common/entities/mm-order.entity.ts
  server/src/modules/strategy/orders.controller.ts
  server/src/modules/strategy/strategy.module.ts
  server/src/modules/strategy/strategy.service.spec.ts
  server/src/modules/strategy/strategy.service.ts
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#147 Tested arb/mm create and fixed backend history bug
  interface/src/i18n/en.json
  interface/src/lib/components/bottomNav/growNewArbNav.svelte
  interface/src/lib/components/dialogs/grow/arbitrage/confirmPayment.svelte
  interface/src/lib/components/dialogs/grow/market_making/confirmPayment.svelte
  interface/src/lib/components/dialogs/orderConfirm.svelte
  interface/src/lib/components/grow/arbitrage/card.svelte
  interface/src/lib/components/grow/arbitrage/details/history.svelte
  interface/src/lib/components/grow/arbitrage/details/infos.svelte
  interface/src/lib/components/grow/arbitrage/new/easy/exchanges.svelte
  interface/src/lib/components/grow/elements/entrance.svelte
  interface/src/lib/components/grow/elements/ongoing.svelte
  interface/src/lib/components/grow/marketMaking/card.svelte
  interface/src/lib/components/grow/marketMaking/new/easy/exchange.svelte
  interface/src/lib/components/topBar/growDetails.svelte
  interface/src/lib/helpers/constants.ts
  interface/src/lib/helpers/hufi/coin.ts
  interface/src/lib/helpers/hufi/strategy.ts
  interface/src/lib/helpers/mixin.ts
  interface/src/lib/helpers/sortTable.ts
  interface/src/lib/stores/market.ts
  interface/src/lib/stores/wallet.ts
  interface/src/routes/(bottomNav)/(grow)/grow/+page.svelte
  interface/src/routes/(secondary)/(grow)/grow/+layout.svelte
  interface/src/routes/(secondary)/(grow)/grow/arbitrage/[id]/+page.svelte
  interface/src/routes/(secondary)/(grow)/grow/arbitrage/[id]/+page.ts
  interface/src/routes/(secondary)/(grow)/grow/market_making/[id]/+page.svelte
  interface/src/routes/(secondary)/(grow)/grow/market_making/[id]/+page.ts
  interface/static/favicon.png
  server/src/app.module.ts
  server/src/common/entities/arbitrage-order.entity.ts
  server/src/common/entities/mm-order.entity.ts
  server/src/modules/mixin/listeners/arbitrage.listener.spec.ts
  server/src/modules/mixin/listeners/arbitrage.listener.ts
  server/src/modules/mixin/listeners/market_making.listener.spec.ts
  server/src/modules/mixin/listeners/market_making.listener.ts
  server/src/modules/mixin/rebalance/rebalance.service.ts
  server/src/modules/strategy/orders.controller.ts
  server/src/modules/strategy/strategy-user.repository.ts
  server/src/modules/strategy/strategy-user.service.spec.ts
  server/src/modules/strategy/strategy-user.service.ts
  server/src/modules/strategy/strategy.controller.ts
  server/src/modules/strategy/strategy.module.ts
  server/src/modules/strategy/strategy.service.spec.ts
  server/src/modules/strategy/strategy.service.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#149 Fine tuning details
  interface/package-lock.json
  interface/package.json
  interface/src/i18n/en.json
  interface/src/i18n/i18n.ts
  interface/src/i18n/zh.json
  interface/src/lib/components/common/connectWalletBtn.svelte
  interface/src/lib/components/grow/arbitrage/card.svelte
  interface/src/lib/components/grow/elements/create.svelte
  interface/src/lib/components/grow/grow.svelte
  interface/src/lib/components/grow/marketMaking/card.svelte
  interface/src/lib/components/home/oauth/connectMixin.svelte
  interface/src/lib/components/home/user/settings.svelte
  interface/src/lib/components/market/candle/price.svelte
  interface/src/lib/components/market/candle/title.svelte
  interface/src/lib/components/topBar/homeBar.svelte
  interface/src/lib/components/topBar/marketBar.svelte
  interface/src/lib/components/wallet/connect/connectWallet.svelte
  interface/src/lib/helpers/sortTable.ts
  interface/src/routes/(secondary)/(homeSecondary)/home/user/i18n/+page.svelte
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#150 Add more tests and update README
  README.md
  interface/src/i18n/en.json
  interface/src/i18n/zh.json
  interface/src/lib/components/bottomNav/growNewArbNav.svelte
  interface/src/lib/components/bottomNav/growNewMMNav.svelte
  interface/src/lib/components/dialogs/candle/candlePairSelector.svelte
  interface/src/lib/components/dialogs/grow/arbitrage/confirmPayment.svelte
  interface/src/lib/components/dialogs/grow/arbitrage/selectExchange.svelte
  interface/src/lib/components/dialogs/grow/arbitrage/selectPair.svelte
  interface/src/lib/components/dialogs/grow/market_making/confirmPayment.svelte
  interface/src/lib/components/dialogs/spotPairSelector.svelte
  interface/src/lib/components/grow/arbitrage/arblist.svelte
  interface/src/lib/components/grow/arbitrage/new/easy/exchanges.svelte
  interface/src/lib/components/grow/elements/entrance.svelte
  interface/src/lib/components/grow/marketMaking/mmlist.svelte
  interface/src/lib/components/grow/marketMaking/new/easy/amount.svelte
  interface/src/lib/components/grow/marketMaking/new/easy/pair.svelte
  interface/src/lib/components/market/candle/title.svelte
  interface/src/lib/components/market/elements/secondTabs.svelte
  interface/src/lib/components/spot/order/elements/orders.svelte
  interface/src/lib/components/topBar/marketBar.svelte
  interface/src/lib/components/topBar/spotBar.svelte
  interface/src/lib/helpers/hufi/coin.test.ts
  interface/src/routes/(secondary)/(grow)/grow/arbitrage/[id]/+page.svelte
  interface/static/mr-market-logo-bg.png
  interface/static/mr-market-logo-transparent.svg
  interface/tests/grow/arbitrage.spec.ts
  interface/tests/grow/market-making.spec.ts
  interface/tests/home/home.spec.ts
  interface/tests/spot/candlestick.spec.ts
  interface/tests/spot/navigation.spec.ts
  interface/tests/spot/trading.spec.ts
  interface/tests/trade/candlestick.spec.ts
  interface/tests/wallet/connect-wallet.spec.ts
Labels: enhancement, Review effort [1-5]: 2, Tests

#151 Update deployment doc
  README.md
Labels: documentation, enhancement, Review effort [1-5]: 1

#152 fix vercel clone url
  README.md
Labels: enhancement, Review effort [1-5]: 1

#154 add root directory parameter to deploy button to make it one click
  README.md
Labels: enhancement, Review effort [1-5]: 1

#155 update deployment in readme
  README.md
Labels: documentation, enhancement, Review effort [1-5]: 1

#158 fix ios input decimal bug
  interface/src/lib/components/grow/arbitrage/new/easy/exchanges.svelte
  interface/src/lib/components/grow/marketMaking/new/easy/amount.svelte
  interface/src/lib/components/spot/bids/inputs.svelte
  interface/src/lib/components/swap/input.svelte
  interface/src/lib/components/swap/output.svelte
Labels: enhancement, Review effort [1-5]: 2, bug_fix
