Repository Hu-Fi/Mr.Market, pull requests merged in 2024-08, with the labels that each got.

#215 Add Volume strat
  server/src/common/helpers/strategyKey.ts
  server/src/modules/exchangeInit/exchangeInit.service.ts
  server/src/modules/strategy/strategy-user.service.ts
  server/src/modules/strategy/strategy.controller.ts
  server/src/modules/strategy/strategy.dto.ts
  server/src/modules/strategy/strategy.service.spec.ts
  server/src/modules/strategy/strategy.service.ts
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#216 Add probit
  server/.env.example
  server/src/modules/exchangeInit/exchangeInit.service.ts
  server/src/modules/strategy/strategy.dto.ts
  server/src/modules/strategy/strategy.service.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#217 Fix marketdata and exchange init module
  server/src/modules/exchangeInit/exchangeInit.service.spec.ts
  server/src/modules/exchangeInit/exchangeInit.service.ts
  server/src/modules/marketdata/marketdata.service.spec.ts
  server/src/modules/marketdata/marketdata.service.ts
Labels: enhancement, Tests, Review effort [1-5]: 4
